### ISSUE TITLE
Cross platform usage

### ISSUE THREAD

**Issue by HugoPeters1024** [TheBoneJarmer/TilarGL#1]
Hey this is a really cool project! I have been wanting for ages to develop OpenGL application with a bit more higher lever control like C# offers. I would love to contribute by the way, so let me know if there are any specific things I can help out with.

I did have one question though, I noticed that you maintain a package for windows and linux separately and I was wondering if it is still possible to create a cross platform application using both. Either by compile time or runtime logic that decides which of the two packages is used. 

Once again, great work!

**Comment by TheBoneJarmer** [comment]
Hi @HugoPeters1024 

Thanks a lot for your kind words! It is definitely possible to create cross-platform applications. I recommend using the Condition attribute in the <PropertyGroup> elements in yours csproj files, like I did with Arqan actually to determine package id's. Like this:

```
<ItemGroup Condition="'$(OS)' == 'UNIX'">
    <PackageReference Include="Arqan.Linux" Version="1.0.1" />
</ItemGroup>
<ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <PackageReference Include="Arqan.Windows.x64" Version="1.0.1" Condition="'$(Configuration)' == 'x64'" />
    <PackageReference Include="Arqan.Windows.x86" Version="1.0.1" Condition="'$(Configuration)' == 'x86'" />
</ItemGroup>
```

I need to add though that my main operating system is Linux Mint and that I use Visual Studio code to build my applications. And with code I can easily modify the command line arguments for dotnet build. So I could just run "dotnet build -c x64". On Windows however I use Visual Studio 2019 and there I noticed that it is not only a configuration but a platform as well. So instead of the itemgroup above you could use this:

```
<ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <PackageReference Include="Arqan.Windows.x64" Version="1.0.1" Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'" />
    <PackageReference Include="Arqan.Windows.x86" Version="1.0.1" Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'" />
<PackageReference Include="Arqan.Windows.x64" Version="1.0.1" Condition="'$(Configuration)|$(Platform)' == 'Release|x64'" />
    <PackageReference Include="Arqan.Windows.x86" Version="1.0.1" Condition="'$(Configuration)|$(Platform)' == 'Release|x86'" />
</ItemGroup>
```

But I gotta admit it is a bit tricky to get Visual Studio budge along with it. Also, it sucks having to need multiple packagereference lines because of the double parameters (platform and configuration). The dotnet build command equivalent for the above would be:
```
dotnet build -c Debug -p:Platform="x64"
dotnet build -c Debug -p:Platform="x86"
dotnet build -c Release -p:Platform="x64"
dotnet build -c Release -p:Platform="x86"
```
Hence I prefer using the Configuration parameter only as that needs less arguments on the command line. But of course you are free to setup it any way you want. I'll admit, it is a shame NuGet does not have some filter where you can upload a package with the same id and version but for different processor architectures and operating systems. If such a thing was possible there would be no need to tweak around like this. D:

That being said, I talked about Configuration and Platform so far but there are many more project properties like that. I recommend peeking at https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019 for a bigger list.

I hope this answers your question. As for contribution, I am always happy if you can get it to work on your machine to start with. I tested Arqan on the few machines I have but obviously everyone has a different cpu and graphics card so other issues may occur on other machines.

With kind regards,
TheBoneJarmer

**Comment by HugoPeters1024** [comment]
Oh nice! I didn't knew that was possible. I honestly thought that dotnet no longer had any secrets for me :). 

I'll try to create an actual application soon but for now I can confirm that ubuntu 20.04 with a GTX 680m worked out of the box with just a black window loop.

**Comment by TheBoneJarmer** [comment]
To be honest, it was not that long ago that I discovered this myself. Up until that point I always maintained two code sources using two branches. I was really amazed to learn how flexible csproj files actually are. And I too have years of experiences with dotnet already so you can imagine how a big a idiot I felt like after learning this xD

Awesome to hear it worked out of the box on Linux by the way! That really is a relief.
