### ISSUE TITLE
glGetShaderInfoLog does not return log

### ISSUE THREAD

**Issue by FireBanana** [TheBoneJarmer/TilarGL#3]
Code is throwing a GL_COMPILE_STATUS error, but glGetShaderInfoLog does not return any info

            int status = -1;
            glGetShaderiv(vertexShader, GL_COMPILE_STATUS, ref status);

            if(status == 0)
            {
                int length = 0;
                byte[] log = new byte[512];

                Console.WriteLine("Vertex error");
                glGetShaderInfoLog(vertexShader, 512, ref length, log);

                foreach (var item in log)
                    Console.Write(item);

                Console.ReadLine();
            }

The "Vertex Error" is printed out but the byte array shows a 1 on the first index followed by 0s. Any help would be appreciated.

**Comment by TheBoneJarmer** [comment]
Hi @FireBanana 

Thanks for reaching out! At first sight your code looks fine. I compared your code with my shader class from Arqanore, which can be found [here](https://github.com/TheBoneJarmer/Arqanore/blob/master/src/Arqanore/Graphics/Shader.cs). And they are almost identical except for variable names.

Therefore I would like to narrow this down. Could you share the entire code where you compile your shader? Perhaps I can detect an error in there. Also, feel free to use my code in your project. I am using Arqanore for my own game and so far it ran fine on both my Windows laptop as my Linux desktop. It is why I am very curious why you get that output.

That being said, I could not help but notice that you try to foreach through your log. This however would give an odd result as the byte array actually represents an ASCII string which you need to convert using Encoding.ASCII.GetString(log). You might want to give that a try and see what output that gives.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
That being said, I noticed you loop through your log using a foreach. I could not help but wonder why as the byte array is actually an ASCII string. You can retrieve its value using Encoding.ASCII.GetString(log). Each element in the array holds a number that represents an ASCII code. Like 65 being the capital 'A' for example. A 0 means literally nothing as it is just empty.

Could you try converting the byte array to a string using the method I described and return the result? I am curious to what that gives.

**Comment by FireBanana** [comment]
Hey @TheBoneJarmer,

Thanks for the response. I have attached the code in a zip file [Program.zip](https://github.com/TheBoneJarmer/Arqan/files/5415864/Program.zip)
I followed the learnopengl.com tutorials, so its a bit messy.

Also, I have already tried Encoding.ASCII.GetString() but when printed out it was blank. So I tried to foreach over the items to see if they had any values stored, but they returned 0.

Thanks again for the help.

**Comment by TheBoneJarmer** [comment]
Hi @FireBanana 

I am currently trying to debug your code. Could you please share the shader files too? Thanks!

With kind regards,
TheBoneJarmer

**Comment by FireBanana** [comment]
These are the shader files that I included
[Shaders.zip](https://github.com/TheBoneJarmer/Arqan/files/5415934/Shaders.zip)

**Comment by TheBoneJarmer** [comment]
Thanks! I just included them in my folder and gave it a shot. And to my surprise it actually ran without an error. I looked at your shader files, they are as basic as it can get and I could not detect any syntax error. However, strangely enough the **glGetShaderiv** function did not return a 0 either when I purposely inserted a syntax error in your shaders files. Which is even more odd. Could be because of our system differences, I don't know.

Therefore I copied the source file of my own shader class and included it in my working folder where your Program.cs is located. And instead of your code I used mine, which actually worked and threw an error as expected. Now, I am not very familiar with shaders and it has been a good while ago since I wrote my shader class but somehow I think it has to do with the order of things. Hence I commented out your code and not erased it. Try to run my version and see if you get an exception. And if so, I do recommend comparing your code with mine and see what the difference is.

Ah, before I forget. I included the shaders you sent in the zip. But I have not reversed my change. When I tried compiling the fragment shader it threw an error due to something else, not the syntax error I purposely inserted.

[Arqan #3.zip](https://github.com/TheBoneJarmer/Arqan/files/5416097/Arqan.3.zip)

**Comment by FireBanana** [comment]
Hey,

Even though the triangle doesnt render, the error log works correctly when I purposely add an error in the shader.

Thanks for the help and the code.

**Comment by TheBoneJarmer** [comment]
You are welcome! If there are any other issues related with Arqan feel free to open up another ticket anytime. And if it may help you learning, I really do recommend looking at Arqanore for that matter. Just look at my code and compare it with yours if you're stuck. I did a lot of learning the same way. In any case, I consider this issue fixed and will therefore close it. Thanks again for reaching out and good luck!

**Comment by FireBanana** [comment]
Thank you, will do.
