### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by ameijboom** [TheBoneJarmer/TilarGL#7]
Hey! I've got a quick question, is there any way this could get MacOS compatibility as well? We're trying to make our project cross-platform so we'd need to have the support here as well. I have a MacBook as well so I can help with testing and try to provide the correct dylib files if needed?

**Comment by TheBoneJarmer** [comment]
Hey @MythicalSora 

As a matter of fact, the only reason Arqan is not compatible with Mac yet is because I don't have a Mac to test it with. So if you would like to help me out with that, that'd be great! Truth is, it does not require that many changes I think. In the **XWGL** class you should extend the following code with the correct dylib names:

```cs
#if Windows

public const string LIBGL = "opengl32.dll";
public const string LIBGLFW = "glfw3.dll";

[DllImport(XWGL.LIBGL, SetLastError = true)]
private static extern IntPtr wglGetProcAddress(string name);

#else

public const string LIBGL = "libGL.so";
public const string LIBGLFW = "libglfw.so";

[DllImport(XWGL.LIBGL, SetLastError = true)]
private static extern IntPtr glXGetProcAddress(string name);

#endif
```

And that should be good enough. No promises of course, maybe you gotta tweak some stuff here and there but assuming Apple did not screw with the symbol names of the OpenGL library, it could be enough. That said, do make certain you have [GLFW](https://github.com/TheBoneJarmer/Arqan#glfw) installed. Idunno if Mac comes with a package manager and if it can be installed like that. But otherwise I am happy to try help you build it from scratch using CMAke and c++ as I have done for Linux too.

**Comment by TheBoneJarmer** [comment]
I just merged my changes to main. Arqan version 2.3.0 should be available as soon as my TeamCity server is done building. I updated the README too while I was at it. The only thing I cannot do I think is publish an official NuGet package for OSX. 

For that I would need some form of Apple server Docker image which I do not know if it exists. What I do know is that Apple is going to drop support for the server operating system they currently have so I have not much hope for that matter. But support is there and I think Mac users are happy to have at least some form of support even if they cannot directly install the NuGet package. For me that is much more important.

Anyhows, I would like to bestow my gratitude once more for helping me out with the OSX support. I added your name to my credits list. That way other OSX users can contact you if they are stuck. I wish I could do more but I am sadly quite limited.
